from PyQt5 import QtCore, QtGui
from PyQt5.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 682)

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)

        self.default_palette = QApplication.palette()
        self.default_style   = QApplication.style()

        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.mainlayout = QGridLayout()
        self.mainlayout.setObjectName("mainlayout")
        spacerItem = QSpacerItem(0, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.mainlayout.addItem(spacerItem, 7, 0, 1, 1)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.title_welcome = QLabel(self.centralwidget)
        self.title_welcome.setBaseSize(QtCore.QSize(800, 25))
        self.title_welcome.setFont(font)
        self.title_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.title_welcome.setObjectName("title_welcome")
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.titlename = QLabel(self.centralwidget)
        self.titlename.setBaseSize(QtCore.QSize(800, 30))
        self.titlename.setFont(font)
        self.titlename.setAlignment(QtCore.Qt.AlignCenter)
        self.titlename.setObjectName("titlename")
        self.software_info1 = QLabel(self.centralwidget)
        self.software_info1.setBaseSize(QtCore.QSize(800, 15))
        self.software_info1.setObjectName("software_info1")
        self.software_info2 = QLabel(self.centralwidget)
        self.software_info2.setBaseSize(QtCore.QSize(800, 15))
        self.software_info2.setObjectName("software_info2")
        self.software_info3 = QLabel(self.centralwidget)
        self.software_info3.setBaseSize(QtCore.QSize(800, 17))
        self.software_info3.setObjectName("software_info3")
        self.mainlayout.addWidget(self.title_welcome, 0, 1, 1, 1)
        self.mainlayout.addWidget(self.titlename, 1, 1, 1, 1)
        self.mainlayout.addWidget(self.software_info1, 2, 1, 1, 1)
        self.mainlayout.addWidget(self.software_info2, 3, 1, 1, 1)
        self.mainlayout.addWidget(self.software_info3, 4, 1, 1, 1)

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.gratinglayout = QGridLayout()
        self.gratinglayout.setObjectName("gratinglayout")
        self.groove_label = QLabel(self.centralwidget)
        self.groove_label.setFont(font)
        self.groove_label.setObjectName("groove_label")
        self.groove_form = QComboBox(self.centralwidget)
        self.groove_form.setObjectName("groove_form")
        self.groove_form.addItem("")
        self.groove_form.addItem("")
        self.groove_form.addItem("")
        self.micro_setting_label = QLabel(self.centralwidget)
        self.micro_setting_label.setFont(font)
        self.micro_setting_label.setObjectName("micro_setting_label")
        self.micro_setting_form = QDoubleSpinBox(self.centralwidget, value=9.00, maximum=22.00, minimum=0.00, singleStep=0.01)
        self.micro_setting_form.setObjectName("micro_setting_form")
        self.feature_label = QLabel(self.centralwidget)
        self.feature_label.setFont(font)
        self.feature_label.setObjectName("feature_label")
        self.feature_form = QLineEdit(self.centralwidget)
        self.feature_form.setObjectName("feature_form")

        self.gratinglayout.addWidget(self.groove_label, 0, 0, 1, 1)
        self.gratinglayout.addWidget(self.groove_form, 0, 1, 1, 1)
        self.gratinglayout.addWidget(self.micro_setting_label, 0, 2, 1, 1)
        self.gratinglayout.addWidget(self.micro_setting_form, 0, 3, 1, 1)
        self.gratinglayout.addWidget(self.feature_label, 0, 4, 1, 1)
        self.gratinglayout.addWidget(self.feature_form, 0, 5, 1, 1)

        self.verticalLayout.addLayout(self.gratinglayout)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.observer_label = QLabel(self.centralwidget)
        self.observer_label.setFont(font)
        self.observer_label.setObjectName("observer_label")
        self.observer_form = QTextEdit(self.centralwidget)
        self.observer_form.setObjectName("observer_form")
        self.observer_form.lineWrapMode()
        self.lamplayout = QGridLayout()
        self.lamplayout.setObjectName("lamplayout")
        self.lamp_label = QLabel(self.centralwidget)
        self.lamp_label.setFont(font)
        self.lamp_label.setObjectName("lamp_label")
        self.lamp_form = QComboBox(self.centralwidget)
        self.lamp_form.setObjectName("lamp_form")
        self.lamp_form.addItem("")
        self.lamp_form.addItem("")
        spacerItem1 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        spacerItem2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.horizontalLayout.addWidget(self.observer_label)
        self.horizontalLayout.addWidget(self.observer_form)
        self.lamplayout.addWidget(self.lamp_label, 2, 1, 1, 1)
        self.lamplayout.addWidget(self.lamp_form, 3, 1, 1, 1)
        self.lamplayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.lamplayout.addItem(spacerItem2, 4, 1, 1, 1)
        self.horizontalLayout.addLayout(self.lamplayout)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.gridLayout_9 = QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.datatype_label = QLabel(self.centralwidget)
        self.datatype_label.setAlignment(QtCore.Qt.AlignCenter)
        self.datatype_label.setObjectName("datatype_label")
        self.datatype_form = QComboBox(self.centralwidget)
        self.datatype_form.setObjectName("datatype_form")
        self.datatype_form.addItem("")
        self.datatype_form.addItem("")
        self.datatype_form.addItem("")
        self.datatype_form.addItem("")
        self.datatype_form.addItem("")
        self.datatype_form.setEnabled(False)
        self.objname_label = QLabel(self.centralwidget)
        self.objname_label.setAlignment(QtCore.Qt.AlignCenter)
        self.objname_label.setObjectName("objname_label")
        self.objname_form = QLineEdit(self.centralwidget)
        self.objname_form.setText("")
        self.objname_form.setObjectName("objname_form")
        self.objname_form.setEnabled(False)
        self.filename_label = QLabel(self.centralwidget)
        self.filename_label.setAlignment(QtCore.Qt.AlignCenter)
        self.filename_label.setObjectName("filename_label")
        self.filename_form = QLineEdit(self.centralwidget)
        self.filename_form.setObjectName("filename_form")
        self.filename_form.setEnabled(False)
        self.bin_label = QLabel(self.centralwidget)
        self.bin_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bin_label.setObjectName("bin_label")
        self.bin_form = QComboBox(self.centralwidget)
        self.bin_form.setObjectName("bin_form")
        self.bin_form.addItem("")
        self.bin_form.addItem("")
        self.bin_form.addItem("")
        self.bin_form.addItem("")
        self.bin_form.setEnabled(False)
        self.exptime_label = QLabel(self.centralwidget)
        self.exptime_label.setAlignment(QtCore.Qt.AlignCenter)
        self.exptime_label.setObjectName("exptime_label")
        self.exptime_form = QDoubleSpinBox(self.centralwidget, value=0., maximum=10000.00, minimum=0.00, singleStep=0.01)
        self.exptime_form.setObjectName("exptime_form")
        self.exptime_form.setEnabled(False)
        self.nexp_label = QLabel(self.centralwidget)
        self.nexp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.nexp_label.setObjectName("nexp_label")
        self.nexp_form = QSpinBox(self.centralwidget, value=1, maximum=50.00, minimum=1, singleStep=1)
        self.nexp_form.setObjectName("nexp_form")
        self.nexp_form.setEnabled(False)

        self.gridLayout_9.addWidget(self.datatype_label, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.datatype_form, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.objname_label, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.objname_form, 1, 1, 1, 1)
        self.gridLayout_9.addWidget(self.filename_label, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.filename_form, 1, 2, 1, 1)
        self.gridLayout_9.addWidget(self.bin_label, 0, 3, 1, 1)
        self.gridLayout_9.addWidget(self.bin_form, 1, 3, 1, 1)
        self.gridLayout_9.addWidget(self.exptime_label, 0, 4, 1, 1)
        self.gridLayout_9.addWidget(self.exptime_form, 1, 4, 1, 1)
        self.gridLayout_9.addWidget(self.nexp_label, 0, 5, 1, 1)
        self.gridLayout_9.addWidget(self.nexp_form, 1, 5, 1, 1)
        self.gridLayout_9.setColumnMinimumWidth(1, 1)
        self.gridLayout_9.setColumnMinimumWidth(2, 2)
        self.gridLayout_9.setColumnMinimumWidth(4, 1)
        self.gridLayout_9.setColumnStretch(1, 1)
        self.gridLayout_9.setColumnStretch(2, 2)
        self.gridLayout_9.setColumnStretch(4, 1)
        self.verticalLayout.addLayout(self.gridLayout_9)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        
        self.gridLayout = QGridLayout()
        self.gridLayout.setSizeConstraint(QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.ccdtemp_label = QLabel(self.centralwidget)
        self.ccdtemp_label.setFont(font)
        self.ccdtemp_label.setObjectName("ccdtemp_label")
        self.ccdtemp_form = QDoubleSpinBox(self.centralwidget, maximum=30.00, minimum=-20.00, singleStep=0.01)
        self.ccdtemp_form.setObjectName("ccdtemp_form")
        self.ccdtemp_form.setValue(-10.)
        self.ambtemp_label = QLabel(self.centralwidget)
        self.ambtemp_label.setFont(font)
        self.ambtemp_label.setObjectName("ambtemp_label")
        self.ambtemp_form = QDoubleSpinBox(self.centralwidget, value=20.00, maximum=50.00, minimum=0.00, singleStep=0.01)
        self.ambtemp_form.setObjectName("ambtemp_form")
        self.ambhum_label = QLabel(self.centralwidget)
        self.ambhum_label.setFont(font)
        self.ambhum_label.setObjectName("ambhum_label")
        self.ambhum_form = QDoubleSpinBox(self.centralwidget, value=50.00, maximum=100.00, minimum=0.00, singleStep=0.01)
        self.ambhum_form.setObjectName("ambhum_form")
        self.skycond_label = QLabel(self.centralwidget)
        self.skycond_label.setFont(font)
        self.skycond_label.setObjectName("skycond_label")
        self.skycond_form = QComboBox(self.centralwidget)
        self.skycond_form.setObjectName("skycond_form")
        self.skycond_form.addItem("")
        self.skycond_form.addItem("")
        self.skycond_form.addItem("")
        self.skycond_form.addItem("")
        self.skycond_form.addItem("")
        self.comment_label = QLabel(self.centralwidget)
        self.comment_label.setFont(font)
        self.comment_label.setObjectName("comment_label")
        self.comment_form = QLineEdit(self.centralwidget)
        self.comment_form.setObjectName("comment_form")

        self.gridLayout.addWidget(self.ccdtemp_label, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.ccdtemp_form, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.ambtemp_label, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.ambtemp_form, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.ambhum_label, 2, 0, 1, 2)
        self.gridLayout.addWidget(self.ambhum_form, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.skycond_label, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.skycond_form, 3, 1, 1, 2)
        self.gridLayout.addWidget(self.comment_label, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.comment_form, 4, 1, 1, 2)
        self.gridLayout.setRowMinimumHeight(0, 1)
        self.gridLayout.setRowMinimumHeight(1, 1)
        self.gridLayout.setRowMinimumHeight(2, 1)
        self.gridLayout.setRowMinimumHeight(3, 1)
        self.gridLayout.setRowMinimumHeight(4, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(2, 2)
        self.mainlayout.addLayout(self.horizontalLayout_2, 6, 1, 1, 1)

        self.tableview = QTableView(self.centralwidget)
        self.tableview.setEnabled(True)
        self.tableview.setMinimumSize(QtCore.QSize(800, 280))
        self.tableview.setBaseSize(QtCore.QSize(800, 280))
        self.tableview.setObjectName("tableview")
        self.tableview.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.mainlayout.addWidget(self.tableview, 7, 1, 1, 1)

        self.confirmlayout = QGridLayout()
        self.confirmlayout.setObjectName("confirmlayout")
        self.nightmode_check = QCheckBox(self.centralwidget)
        self.nightmode_check.setObjectName("nightmode_check")
        self.startlog_button = QPushButton(self.centralwidget)
        self.startlog_button.setObjectName("startlog_button")
        self.updatelog_button = QPushButton(self.centralwidget)
        self.updatelog_button.setEnabled(False)
        self.updatelog_button.setObjectName("updatelog_button")
        self.savelog_button = QPushButton(self.centralwidget)
        self.savelog_button.setEnabled(False)
        self.savelog_button.setObjectName("savelog_button")
        self.resetlog_button = QPushButton(self.centralwidget)
        self.resetlog_button.setEnabled(False)
        self.resetlog_button.setObjectName("resetlog_button")
        self.closewindow_button = QPushButton(self.centralwidget)
        self.closewindow_button.setObjectName("closewindow_button")
        spacerItem3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.confirmlayout.addWidget(self.nightmode_check, 0, 0, 1, 1)
        self.confirmlayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.confirmlayout.addWidget(self.startlog_button, 0, 2, 1, 1)
        self.confirmlayout.addWidget(self.updatelog_button, 0, 3, 1, 1)
        self.confirmlayout.addWidget(self.savelog_button, 0, 4, 1, 1)
        self.confirmlayout.addWidget(self.resetlog_button, 0, 5, 1, 1)
        self.confirmlayout.addWidget(self.closewindow_button, 0, 6, 1, 1)
        self.mainlayout.addLayout(self.confirmlayout, 8, 1, 1, 1)
        
        self.line = QFrame(self.centralwidget)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setObjectName("line")
        self.mainlayout.addWidget(self.line, 5, 1, 1, 1)
        self.mainlayout.setRowStretch(6, 1)
        self.mainlayout.setRowStretch(7, 3)
        self.gridLayout_4.addLayout(self.mainlayout, 0, 0, 1, 1)
        spacerItem4 = QSpacerItem(40, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 1, 0, 1, 1)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.groove_label.setBuddy(self.groove_form)
        self.micro_setting_label.setBuddy(self.micro_setting_form)
        self.feature_label.setBuddy(self.feature_form)
        self.observer_label.setBuddy(self.observer_form)
        self.lamp_label.setBuddy(self.lamp_form)
        self.ccdtemp_label.setBuddy(self.ccdtemp_form)
        self.ambtemp_label.setBuddy(self.ambtemp_form)
        self.skycond_label.setBuddy(self.skycond_form)
        self.ambhum_label.setBuddy(self.ambhum_form)
        self.comment_label.setBuddy(self.comment_form)
        self.datatype_label.setBuddy(self.datatype_form)
        self.objname_label.setBuddy(self.objname_form)
        self.filename_label.setBuddy(self.filename_form)
        self.bin_label.setBuddy(self.bin_form)
        self.exptime_label.setBuddy(self.exptime_form)
        self.nexp_label.setBuddy(self.nexp_form)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.nightmode_check, self.startlog_button)
        MainWindow.setTabOrder(self.startlog_button, self.updatelog_button)
        MainWindow.setTabOrder(self.updatelog_button, self.savelog_button)
        MainWindow.setTabOrder(self.savelog_button, self.resetlog_button)
        MainWindow.setTabOrder(self.resetlog_button, self.closewindow_button)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LHIRES Telescope Data Logging Software"))
        self.title_welcome.setText(_translate("MainWindow", "Welcome to"))
        self.titlename.setText(_translate("MainWindow", "LHIRES Telescope Data Logging Software"))
        self.software_info2.setText(_translate("MainWindow", "version: 2.0"))
        self.software_info1.setText(_translate("MainWindow", "by: Irfan Imaduddin"))
        self.software_info3.setText(_translate("MainWindow", "contact: irfanimaduddin[at]gmail[dot]com"))
        self.groove_label.setText(_translate("MainWindow", "Grating"))
        self.groove_form.setItemText(0, _translate("MainWindow", "600 g/mm"))
        self.groove_form.setItemText(1, _translate("MainWindow", "1200 g/mm"))
        self.groove_form.setItemText(2, _translate("MainWindow", "2400 g/mm"))
        self.micro_setting_label.setText(_translate("MainWindow", "Micrometer Setting"))
        self.feature_label.setText(_translate("MainWindow", "Spectral Feature"))
        self.observer_label.setText(_translate("MainWindow", "Observer(s)"))
        self.lamp_label.setText(_translate("MainWindow", "Comparison Lamp"))
        self.lamp_form.setItemText(0, _translate("MainWindow", "NeAr"))
        self.lamp_form.setItemText(1, _translate("MainWindow", "FeNeAr"))
        self.datatype_label.setText(_translate("MainWindow", "Datatype"))
        self.datatype_form.setItemText(0, _translate("MainWindow", "Object"))
        self.datatype_form.setItemText(1, _translate("MainWindow", "Comparison"))
        self.datatype_form.setItemText(2, _translate("MainWindow", "Bias"))
        self.datatype_form.setItemText(3, _translate("MainWindow", "Dark"))
        self.datatype_form.setItemText(4, _translate("MainWindow", "Flat"))
        self.objname_label.setText(_translate("MainWindow", "Object Name"))
        self.filename_label.setText(_translate("MainWindow", "File Name"))
        self.bin_label.setText(_translate("MainWindow", "Bin"))
        self.bin_form.setItemText(0, _translate("MainWindow", "1"))
        self.bin_form.setItemText(1, _translate("MainWindow", "2"))
        self.bin_form.setItemText(2, _translate("MainWindow", "3"))
        self.bin_form.setItemText(3, _translate("MainWindow", "4"))
        self.exptime_label.setText(_translate("MainWindow", "Exptime"))
        self.nexp_label.setText(_translate("MainWindow", "N"))
        self.ccdtemp_label.setText(_translate("MainWindow", "CCD Temperature (C)"))
        self.ambtemp_label.setText(_translate("MainWindow", "Ambient Temperature (C)"))
        self.ambhum_label.setText(_translate("MainWindow", "Ambient Humidity (%)"))
        self.skycond_label.setText(_translate("MainWindow", "Sky Condition"))
        self.skycond_form.setItemText(0, _translate("MainWindow", "Good"))
        self.skycond_form.setItemText(1, _translate("MainWindow", "Variable"))
        self.skycond_form.setItemText(2, _translate("MainWindow", "Hazy"))
        self.skycond_form.setItemText(3, _translate("MainWindow", "Cloudy"))
        self.skycond_form.setItemText(4, _translate("MainWindow", "Rain"))
        self.comment_label.setText(_translate("MainWindow", "Comment(s)"))
        self.nightmode_check.setText(_translate("MainWindow", "Night Mode"))
        self.startlog_button.setText(_translate("MainWindow", "Start"))
        self.updatelog_button.setText(_translate("MainWindow", "Update"))
        self.savelog_button.setText(_translate("MainWindow", "End && Save"))
        self.resetlog_button.setText(_translate("MainWindow", "Reset"))
        self.closewindow_button.setText(_translate("MainWindow", "Exit"))